//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace TransportAPP.WebReference {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="TransportWSSoap", Namespace="http://www.transportservice.com/")]
    public partial class TransportWS : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SaludoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetUsuariosOperationCompleted;
        
        private System.Threading.SendOrPostCallback ExisteUsuarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback InsertaUsuarioOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public TransportWS() {
            this.Url = global::TransportAPP.Properties.Settings.Default.TransportAPP_WebReference_TransportWS;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SaludoCompletedEventHandler SaludoCompleted;
        
        /// <remarks/>
        public event GetUsuariosCompletedEventHandler GetUsuariosCompleted;
        
        /// <remarks/>
        public event ExisteUsuarioCompletedEventHandler ExisteUsuarioCompleted;
        
        /// <remarks/>
        public event InsertaUsuarioCompletedEventHandler InsertaUsuarioCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.transportservice.com/Saludo", RequestNamespace="http://www.transportservice.com/", ResponseNamespace="http://www.transportservice.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Saludo(string nombre) {
            object[] results = this.Invoke("Saludo", new object[] {
                        nombre});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SaludoAsync(string nombre) {
            this.SaludoAsync(nombre, null);
        }
        
        /// <remarks/>
        public void SaludoAsync(string nombre, object userState) {
            if ((this.SaludoOperationCompleted == null)) {
                this.SaludoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSaludoOperationCompleted);
            }
            this.InvokeAsync("Saludo", new object[] {
                        nombre}, this.SaludoOperationCompleted, userState);
        }
        
        private void OnSaludoOperationCompleted(object arg) {
            if ((this.SaludoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SaludoCompleted(this, new SaludoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.transportservice.com/GetUsuarios", RequestNamespace="http://www.transportservice.com/", ResponseNamespace="http://www.transportservice.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetUsuarios() {
            object[] results = this.Invoke("GetUsuarios", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetUsuariosAsync() {
            this.GetUsuariosAsync(null);
        }
        
        /// <remarks/>
        public void GetUsuariosAsync(object userState) {
            if ((this.GetUsuariosOperationCompleted == null)) {
                this.GetUsuariosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUsuariosOperationCompleted);
            }
            this.InvokeAsync("GetUsuarios", new object[0], this.GetUsuariosOperationCompleted, userState);
        }
        
        private void OnGetUsuariosOperationCompleted(object arg) {
            if ((this.GetUsuariosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUsuariosCompleted(this, new GetUsuariosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.transportservice.com/ExisteUsuario", RequestNamespace="http://www.transportservice.com/", ResponseNamespace="http://www.transportservice.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool ExisteUsuario(string usuario) {
            object[] results = this.Invoke("ExisteUsuario", new object[] {
                        usuario});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void ExisteUsuarioAsync(string usuario) {
            this.ExisteUsuarioAsync(usuario, null);
        }
        
        /// <remarks/>
        public void ExisteUsuarioAsync(string usuario, object userState) {
            if ((this.ExisteUsuarioOperationCompleted == null)) {
                this.ExisteUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnExisteUsuarioOperationCompleted);
            }
            this.InvokeAsync("ExisteUsuario", new object[] {
                        usuario}, this.ExisteUsuarioOperationCompleted, userState);
        }
        
        private void OnExisteUsuarioOperationCompleted(object arg) {
            if ((this.ExisteUsuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ExisteUsuarioCompleted(this, new ExisteUsuarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.transportservice.com/InsertaUsuario", RequestNamespace="http://www.transportservice.com/", ResponseNamespace="http://www.transportservice.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void InsertaUsuario(string usuario, string clave) {
            this.Invoke("InsertaUsuario", new object[] {
                        usuario,
                        clave});
        }
        
        /// <remarks/>
        public void InsertaUsuarioAsync(string usuario, string clave) {
            this.InsertaUsuarioAsync(usuario, clave, null);
        }
        
        /// <remarks/>
        public void InsertaUsuarioAsync(string usuario, string clave, object userState) {
            if ((this.InsertaUsuarioOperationCompleted == null)) {
                this.InsertaUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsertaUsuarioOperationCompleted);
            }
            this.InvokeAsync("InsertaUsuario", new object[] {
                        usuario,
                        clave}, this.InsertaUsuarioOperationCompleted, userState);
        }
        
        private void OnInsertaUsuarioOperationCompleted(object arg) {
            if ((this.InsertaUsuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InsertaUsuarioCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void SaludoCompletedEventHandler(object sender, SaludoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SaludoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SaludoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GetUsuariosCompletedEventHandler(object sender, GetUsuariosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUsuariosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUsuariosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void ExisteUsuarioCompletedEventHandler(object sender, ExisteUsuarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ExisteUsuarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ExisteUsuarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void InsertaUsuarioCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591